// Veil proof bundle — the off-chain proving artifact (NFR-4).
//
// Proving runs OFF-CHAIN, never in the browser, and the RISC Zero Groth16 wrap
// needs an x86 + Docker host (it OOMs on an 8GB Apple Silicon Mac). So for the
// demo this bundle is a REAL Groth16 proof generated by the `groth16-proof`
// GitHub Actions workflow (x86 runner) and committed to the repo. The /api/proof
// endpoint serves it; the frontend submits it to the veil contract's `commit`.
//
// This is honest: the proof is genuine and verifies on-chain. What is "canned"
// is only that we reuse one pregenerated proof for the deterministic demo inputs
// (X=10000, private W=(500,1), salt=0x07*32 → Y=10500), rather than spinning up a
// fresh CI run per click. A production deployment would call the proving service
// live per prediction — the architecture (frontend → proving backend → proof) is
// already exactly that shape.
//
// The values below are read from the artifact in this folder:
//   demo-proof.txt  : seal / image_id / journal_digest   (run 27517701926)
//   demo-commit.txt : x_hash / commitment_c / y / salt

/** The off-chain prediction: the predictor's private model + inputs. */
export const DEMO_PREDICTION = {
  /** Public market input X (price in cents → $100.00). */
  x: 10000,
  /** Private bias weight w0 (never leaves the prover). */
  w0: 500,
  /** Private slope weight w1 (never leaves the prover). */
  w1: 1,
  /** Resulting forecast Y = w0 + w1*X = 10500 (price in cents → $105.00). */
  y: 10500,
} as const;

/**
 * The Groth16 proof bundle the predictor submits to `commit`.
 *
 * `sealHex` is large (260 bytes); the /api/proof route parses it from
 * `demo-proof.txt` at request time and returns it to the client, so the seal
 * lives in the artifact, not inline here. `imageIdHex` / `journalDigestHex` are
 * the stable identifiers, kept here for reference + verification.
 */
export const DEMO_PROOF = {
  /** Canonical CI guest image id (hex). Matches the live contract's init. */
  imageIdHex:
    "bec2f7035708f6ad9345b052b9066ea4cc3095eeace1e4e150bdb2aaaddcf043",
  /** sha256(journal) where journal = x_hash || C. */
  journalDigestHex:
    "452f167c0aaec2ca1d423af4ede792de1c03b8811592ebcc8ca937c5a4863e5c",
} as const;

/** The two journal halves the predictor commits now (public). */
export const DEMO_COMMITMENT = {
  /** sha256(X_le16) — binds the proof to this market snapshot. */
  xHashHex:
    "9eac591028026a7fcc076a9659f8b7219fe106a24de92e57831ba62c283f410d",
  /** C = sha256(Y_le16 || salt) — the commitment stored on-chain. */
  commitmentCHex:
    "08ff5ca389d479d3564e98552d92e12b265a6d32f8f5aa4f571a1481ef674d0b",
} as const;

/** What the predictor keeps secret until reveal (FR-6). */
export const DEMO_REVEAL = {
  /** The forecast value Y (revealed after the event). */
  y: 10500,
  /** The 32-byte blinding salt (hex). */
  saltHex:
    "0707070707070707070707070707070707070707070707070707070707070707",
} as const;
