import { readFile } from "node:fs/promises";
import path from "node:path";
import { NextResponse } from "next/server";
import { DEMO_PREDICTION, DEMO_COMMITMENT, DEMO_PROOF } from "@/lib/proof";

// GET /api/proof — the off-chain proving service (NFR-4).
//
// The browser NEVER proves. It asks this server endpoint for a Groth16 proof,
// which it then submits to the veil contract's `commit`. For the demo this
// serves a REAL proof pregenerated by the `groth16-proof` GitHub Actions
// workflow (x86 + Docker — the wrap can't run on the dev Mac). A production
// deployment would invoke the prover live here per prediction; the shape
// (frontend → this endpoint → proof) is already that of a proving service.
//
// Returns everything the client needs for `commit(predictor, seal, x_hash, C)`.

export const dynamic = "force-dynamic";

export async function GET() {
  try {
    const proofPath = path.join(process.cwd(), "lib", "proof", "demo-proof.txt");
    const raw = await readFile(proofPath, "utf8");
    const [sealHex, imageIdHex, journalDigestHex] = raw
      .trim()
      .split("\n")
      .map((l) => l.trim());

    if (!sealHex || !imageIdHex || !journalDigestHex) {
      throw new Error("demo-proof.txt malformed");
    }

    // Sanity: the artifact's image id must match what we expect (and what the
    // live contract was initialized with). A mismatch means the CI runner
    // changed the guest image id — surface it instead of silently committing a
    // proof the contract will reject.
    if (imageIdHex !== DEMO_PROOF.imageIdHex) {
      return NextResponse.json(
        {
          error: "image_id_mismatch",
          detail:
            "Pregenerated proof image id differs from the expected canonical id. " +
            "Regenerate the proof in CI and/or call set_image_id on the contract.",
          expected: DEMO_PROOF.imageIdHex,
          got: imageIdHex,
        },
        { status: 409 },
      );
    }

    return NextResponse.json({
      // The proof bundle for on-chain verification.
      sealHex,
      imageIdHex,
      journalDigestHex,
      // The two public journal halves the predictor commits.
      xHashHex: DEMO_COMMITMENT.xHashHex,
      commitmentCHex: DEMO_COMMITMENT.commitmentCHex,
      // Human-facing context (the public input + the resulting forecast).
      prediction: {
        x: DEMO_PREDICTION.x,
        y: DEMO_PREDICTION.y, // shown only AFTER the proof is generated; on-chain it stays hidden until reveal
      },
      meta: {
        source: "github-actions:groth16-proof",
        note: "Real RISC Zero Groth16 proof; weights W never appear in the journal.",
      },
    });
  } catch (err) {
    return NextResponse.json(
      {
        error: "proof_unavailable",
        detail: err instanceof Error ? err.message : String(err),
      },
      { status: 500 },
    );
  }
}
